# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            blogdemo
tagline:          A demonstration of blogging with github pages
url:              
paginate:         1
baseurl:          /
author:
  name:           
  url:            
  email:          

# Custom vars
version:          
github:
  repo:           
